modLoader = "javafml"
loaderVersion = "[41,49]"
issueTrackerURL = "https://github.com/JustDoom/StopDropNRoll/issues"
license = "MIT"

[[mods]]
modId = "stopdropnroll"
version = "${version}"
displayName = "Stop Drop N Roll"
authors = "JustDoom"
description = '''
When you're on fire, stop, drop, and roll
'''
#logoFile = ""

[[dependencies.stopdropnroll]]
modId = "forge"
mandatory = true
versionRange = "[41,49]"
ordering = "NONE"
side = "SERVER"

[[dependencies.stopdropnroll]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20.4]"
ordering = "NONE"
side = "BOTH"