modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/JustDoom/StopDropNRoll/issues"
license = "MIT"

[[mods]]
modId = "stopdropnroll"
version = "${version}"
displayName = "Stop Drop N Roll"
authors = "JustDoom"
description = '''
When you're on fire, stop, drop, and roll
'''
#logoFile = ""

[[dependencies.stopdropnroll]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stopdropnroll]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stopdropnroll]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"