modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/JustDoom/StopDropNRoll/issues"
license = "MIT"

[[mods]]
modId = "stopdropnroll"
version = "${version}"
displayName = "Stop Drop N Roll"
authors = "JustDoom"
description = '''
When you're on fire, stop, drop, and roll
'''
#logoFile = ""

[[dependencies.stopdropnroll]]
modId = "neoforge"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stopdropnroll]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "stopdropnroll-common.mixins.json"